app = 'vers-service-session'
primary_region = 'syd'

[build]

[env]
  NODE_ENV = "production"
  LOGGING = "info"
  HOSTNAME = "fly-local-6pn"
  PORT = "3002"
  API_IDENTIFIER = "https://api.versidle.com/"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 3002
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
