app = 'vers-service-session'
primary_region = 'syd'

[build]

[env]
  NODE_ENV = "production"
  LOGGING = "info"
  HOSTNAME = "fly-local-6pn"
  PORT = "3002"
  API_IDENTIFIER = "https://api.versidle.com/"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1