services:
  mongo:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo:/data/db
    expose:
      - '27017'
    ports:
      - '27017:27017'
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vers
      - PGPORT=5433
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - '5433'
    ports:
      - '5433:5433'
  service-api:
    build:
      context: .
      dockerfile: projects/service-api/Dockerfile
      args:
        BUILD_MODE: development
    env_file:
      - projects/service-api/.env.development
    environment:
      - EMAILS_SERVICE_URL=http://service-email:3001/
      - SESSIONS_SERVICE_URL=http://service-session:3002/
      - USERS_SERVICE_URL=http://service-user:3003/
      - VERIFICATIONS_SERVICE_URL=http://service-verification:3004/
    expose:
      - '3000'
    ports:
      - '3000:3000'
  service-avatar:
    build:
      context: .
      dockerfile: projects/service-avatar/Dockerfile
      args:
        BUILD_MODE: development
    env_file:
      - projects/service-avatar/.env.development
      - projects/service-avatar/.env.development.local
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5433/vers
    ports:
      - '3005:3005'
    depends_on:
      - postgres
  service-email:
    build:
      context: .
      dockerfile: projects/service-email/Dockerfile
      args:
        BUILD_MODE: development
    env_file:
      - projects/service-email/.env.development
      - projects/service-email/.env.development.local
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5433/vers
    ports:
      - '3001:3001'
    depends_on:
      - postgres
  service-session:
    build:
      context: .
      dockerfile: projects/service-session/Dockerfile
      args:
        BUILD_MODE: development
    env_file:
      - projects/service-session/.env.development
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5433/vers
    ports:
      - '3002:3002'
    depends_on:
      - postgres
  service-user:
    build:
      context: .
      dockerfile: projects/service-user/Dockerfile
      args:
        BUILD_MODE: development
    env_file:
      - projects/service-user/.env.development
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5433/vers
    ports:
      - '3003:3003'
    depends_on:
      - postgres
  service-verification:
    build:
      context: .
      dockerfile: projects/service-verification/Dockerfile
      args:
        BUILD_MODE: development
    env_file:
      - projects/service-verification/.env.development
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5433/vers
    ports:
      - '3004:3004'
    depends_on:
      - postgres
volumes:
  postgres:
