app = 'vers-mongo'
primary_region = 'syd'

[build]

[env]
  NODE_ENV = "production"
  LOGGING = "info"
  HOSTNAME = "0.0.0.0"
  PORT = "5500"

[[mounts]]
  source = 'mongo_data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.role]
    port = 5500
    type = 'http'
    interval = '5s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/flycheck/role'

  [checks.vm]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '1s'
    method = 'get'
    path = '/flycheck/vm'
