app = 'vers-service-email'
primary_region = 'syd'

[build]

[env]
  API_IDENTIFIER = 'https://api.versidle.com/'
  HOSTNAME = 'fly-local-6pn'
  LOGGING = 'info'
  NODE_ENV = 'production'
  PORT = '3001'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
