app = 'vers-service-user'
primary_region = 'syd'

[build]

[env]
  API_IDENTIFIER = 'https://api.versidle.com/'
  HOSTNAME = 'fly-local-6pn'
  LOGGING = 'info'
  NODE_ENV = 'production'
  PORT = '3003'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 3003
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
